name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: docker.pkg.github.com/rdaniels6813/dev-go/go
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          registry: docker.pkg.github.com
          tags: "latest,1.14.6"
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: rdaniels6813/dev-go
          username: rdaniels6813
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          tag_semver: true
          tags: "latest,1.14.6"
